name: CI for Testing User

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: user-api-tests
    runs-on: ubuntu-latest

    # Reading env variables from github secrets
    env:
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_USER_NAME: ${{ secrets.DATABASE_USER_NAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      IS_TEST_ENVIROMENT: ${{ secrets.IS_TEST_ENVIROMENT }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3

        # The step where we install postgres is referenced from
        # https://www.digitalocean.com/community/tutorials/how-to-install-postgresql-on-ubuntu-20-04-quickstart
      - name: install postgres
        run: |
          sudo apt update
          sudo apt install postgresql postgresql-contrib -y
          sudo systemctl start postgresql.service

      - name: Add webaapp log directory under /var/log
        run: |
          sudo mkdir /var/log/webapp

      - name: create env file for webapp
        run: |
          touch .env
          echo "IS_TEST_ENVIROMENT=${IS_TEST_ENVIROMENT}" >> .env

      # Referenced from to create DB, a new user and granting them necessary permissions
      # https://medium.com/@mohammedhammoud/postgresql-create-user-create-database-grant-privileges-access-aabb2507c0aa
      - name: create a new DB and update the user password via secrets
        run: |
          sudo -u postgres psql -c "CREATE DATABASE ${{ env.DATABASE_NAME }};"
          sudo -u postgres psql -c "CREATE USER ${{env.DATABASE_USER_NAME}} PASSWORD '${{env.DATABASE_PASSWORD}}';"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE ${{ env.DATABASE_NAME }} TO ${{ env.DATABASE_USER_NAME }};"

      - run: npm install
      - run: npm test
